apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3-unstract
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
parameters:
  type: gp3
  encrypted: "true"
  tagSpecification_1: "Environment=int"
  tagSpecification_2: "Team=forsys"
  tagSpecification_3: "org:cmdbid=na"
  tagSpecification_4: "org:dataclassification=public"
 #tagSpecification_5: "karpenter.k8s.aws/ec2nodeclass=llmwhisperer"
  tagSpecification_5: "org:automation:env=int"
  tagSpecification_6: "org:teamname=cloud"
  tagSpecification_7: "org:repo=SP5FT/terraform-aws-eks-ejm"
  tagSpecification_8: "org:appname=eks"
  tagSpecification_9: "org:stack=058264298758-ejm-int-unwrapped"
  tagSpecification_10: "eks:eks-cluster-name=ejm-int"
  tagSpecification_11: "org:domain=ejm"
  tagSpecification_12: "dr:rpo=1h"
  tagSpecification_13: "org:appsuite=eks"
  tagSpecification_14: "org:branch=main"
  tagSpecification_15: "org:publicfacing=false"
 # tagSpecification_17: "karpenter.sh/nodepool=llmwhisperer"
  tagSpecification_16: "org:compliance=na"
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true